import os

def is_auto_generated_file(content, file_path):
    """
    Проверяет, является ли файл автоматически сгенерированным или миграцией
    """
    # Список признаков автогенерации в содержимом
    auto_generate_markers = [
        "Auto-generated",
        "autogenerated",
        "Automatically generated",
        "auto-generated",
        "Generated code",
        "CodeGenerator",
        "Generated by",
        "generated by",
        "<auto-generated",
        "// <auto-generated>",
        "#pragma warning disable",
        "//------------------------------------------------------------------------------",
        "// <autogenerated",
        "Tool-generated",
        "Designer generated",
        "DesignerFile",
    ]
    
    # Признаки миграций Entity Framework
    migration_markers = [
        "Migration",
        "migration",
        "MigrationBuilder",
        "migrationBuilder",
        "Up(MigrationBuilder",
        "Down(MigrationBuilder",
        "partial class Migration",
        "Microsoft.EntityFrameworkCore.Migrations",
        "EF Core migration",
        "BuildTargetModel",
        "Snapshot.cs",
    ]
    
    # Проверка по имени файла
    filename_lower = os.path.basename(file_path).lower()
    
    # Пропускаем файлы миграций по имени
    if "migration" in filename_lower:
        return True
    
    if any(marker.lower() in filename_lower for marker in [".designer.cs", ".g.cs", ".generated.cs"]):
        return True
    
    # Проверка пути (папки миграций)
    path_lower = file_path.lower()
    if "migrations" in path_lower or "migration" in path_lower:
        # Дополнительная проверка: если файл лежит в папке Migrations - почти наверняка миграция
        if "migrations" in path_lower.split(os.sep):
            return True
    
    # Проверка первых 5000 символов содержимого (обычно маркеры в начале)
    content_start = content[:5000] if content else ""
    
    for marker in auto_generate_markers:
        if marker in content_start:
            return True
    
    for marker in migration_markers:
        if marker in content_start:
            return True
    
    return False

def collect_cs_files_to_txt(root_dir, output_file):
    """
    Рекурсивно обходит root_dir, находит все .cs файлы (кроме автогенерируемых и миграций),
    и записывает их содержимое в output_file
    """
    processed_count = 0
    skipped_count = 0
    error_count = 0
    
    with open(output_file, 'w', encoding='utf-8') as out_f:
        for dirpath, dirnames, filenames in os.walk(root_dir):
            # Игнорируем стандартные папки с автогенерируемым кодом и миграциями
            dirnames[:] = [d for d in dirnames if d not in [
                'obj', 'bin', 'node_modules', '.git', '.vs',
                'Migrations', 'migrations',  # Папки миграций EF
                'Migration'
            ]]
            
            for filename in filenames:
                if not filename.endswith('.cs'):
                    continue
                
                file_path = os.path.join(dirpath, filename)
                
                # Быстрая проверка по имени файла перед чтением
                filename_lower = filename.lower()
                if any(x in filename_lower for x in ['migration', 'snapshot']):
                    print(f"⚠️ Пропущена миграция: {file_path}")
                    skipped_count += 1
                    continue
                
                try:
                    # Пробуем прочитать файл
                    try:
                        with open(file_path, 'r', encoding='utf-8') as cs_f:
                            content = cs_f.read()
                    except UnicodeDecodeError:
                        # Пробуем другие кодировки
                        try:
                            with open(file_path, 'r', encoding='windows-1251') as cs_f:
                                content = cs_f.read()
                        except:
                            with open(file_path, 'r', encoding='latin-1') as cs_f:
                                content = cs_f.read()
                    
                    # Проверяем, является ли файл автогенерируемым или миграцией
                    if is_auto_generated_file(content, file_path):
                        print(f"⚠️ Пропущен (автогенерация/миграция): {file_path}")
                        skipped_count += 1
                        continue
                    
                    # Записываем в выходной файл
                    out_f.write(f"[{filename}]\n")
                    out_f.write(content)
                    out_f.write("\n\n")
                    
                    print(f"✅ Обработан: {file_path}")
                    processed_count += 1
                
                except Exception as e:
                    print(f"❌ Ошибка при чтении {file_path}: {e}")
                    error_count += 1
    
    return processed_count, skipped_count, error_count

def show_preview(output_file, num_lines=50):
    """Показывает预览 первых строк результата"""
    if os.path.exists(output_file):
        print(f"\n{'='*50}")
        print("📖 Превью результата (первые 50 строк):")
        print('='*50)
        with open(output_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()[:num_lines]
            for line in lines:
                print(line.rstrip())
        print('='*50)

if __name__ == "__main__":
    # Путь к вашей папке
    search_directory = r"C:\Users\aydar\Desktop\diplom\diplom-queue"
    output_txt = r"C:\Users\aydar\Desktop\diplom\project.txt"
    
    print(f"📁 Поиск .cs файлов в: {search_directory}")
    print("⏳ Игнорируются:")
    print("   - Автогенерируемые файлы (designer, auto-generated и т.д.)")
    print("   - Миграции Entity Framework (Migrations)")
    print("   - Папки: obj, bin, Migrations, .git, .vs\n")
    
    processed, skipped, errors = collect_cs_files_to_txt(search_directory, output_txt)
    
    print(f"\n{'='*50}")
    print(f"✅ Готово!")
    print(f"📄 Обработано ручных файлов: {processed}")
    print(f"⚠️ Пропущено (автогенерация/миграции): {skipped}")
    print(f"❌ Ошибок: {errors}")
    print(f"📁 Результат сохранён в: {os.path.abspath(output_txt)}")
    
    # Показать превью результата
    if processed > 0:
        show_preview(output_txt)