// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20260429114359_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("IconName")
                        .HasColumnType("text")
                        .HasColumnName("icon_name");

                    b.Property<string>("Letter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("letter");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_services_parent_id");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfc3d5c0-69fc-4ac1-a593-473b945dd3bc"),
                            Description = "Запись на первичный прием, заведение медицинских карт и предоставление справочной информации о работе клиники.",
                            IconName = "Book",
                            Letter = "A",
                            Name = "Регистратура"
                        },
                        new
                        {
                            Id = new Guid("99c48a22-122d-4821-afea-2b2b345e592c"),
                            Description = "Оформление и оплата медицинских услуг, не входящих в программу ОМС.",
                            IconName = "Ruble",
                            Letter = "B",
                            Name = "Платные услуги"
                        },
                        new
                        {
                            Id = new Guid("7370aa38-cbb9-4220-915d-ce042194f24e"),
                            Description = "Лабораторная диагностика от общих анализов крови до генетических исследований.",
                            IconName = "Lab",
                            Letter = "C",
                            Name = "Анализы"
                        },
                        new
                        {
                            Id = new Guid("9d78a673-efa3-4af3-9828-55515d26e134"),
                            Description = "Выбор специалиста и бронирование подходящего времени визита.",
                            IconName = "Clock",
                            Name = "Запись на прием к врачу",
                            ParentId = new Guid("dfc3d5c0-69fc-4ac1-a593-473b945dd3bc")
                        },
                        new
                        {
                            Id = new Guid("d320728d-0a5e-490c-be3c-04bcf3a7a4c8"),
                            Description = "Официальное подтверждение временной нетрудоспособности.",
                            IconName = "CheckBook",
                            Name = "Оформление больничного",
                            ParentId = new Guid("dfc3d5c0-69fc-4ac1-a593-473b945dd3bc")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan?>("EstimationTime")
                        .HasColumnType("interval")
                        .HasColumnName("estimation_time");

                    b.Property<string>("Facets")
                        .HasColumnType("jsonb")
                        .HasColumnName("facets");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("WindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("window_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Service", b =>
                {
                    b.HasOne("Domain.Entities.Service", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_services_services_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Service", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
